server:
  port: 8085

spring:
  config:
    import: optional:file:../../.env[.properties]
  application:
    name: portfolio-service
  datasource:
    url: ${PORTFOLIO_DB_URL}
    username: ${PORTFOLIO_DB_USERNAME}
    password: ${PORTFOLIO_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: portfolio-service

marketquest:
  kafka:
    topic:
      trade-executed: trade.executed
