spring.application.name=watchlist-service
spring.config.import=optional:file:../../.env[.properties]
server.port=8082



spring.datasource.url=jdbc:mysql://localhost:3307/marketquest_auth
spring.datasource.username=marketquest_user
spring.datasource.password=MarketQuest@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.mail.host=${SMTP_HOST:}
spring.mail.port=${SMTP_PORT:587}
spring.mail.username=${SMTP_USERNAME:}
spring.mail.password=${SMTP_PASSWORD:}
spring.mail.properties.mail.smtp.auth=${SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${SMTP_STARTTLS_ENABLE:true}
marketquest.otp.email.from=${OTP_EMAIL_FROM:}
